### 게시물 목록
GET http://localhost:9999/shop/boards
Content-Type: application/json

### 게시물 등록
POST http://localhost:9999/shop/boards
Content-Type: application/json

{
    "title": "게시판 등록 테스트123",
    "writer": "sohee",
    "content": "마이바티스로 보내는 내용"
}

### 게시물 한 건 조회
GET http://localhost:9999/shop/boards/4
Content-Type: application/json

### 게시물 수정
PUT http://localhost:9999/shop/boards/3
Content-Type: application/json

{
    "title": "게시판 등록 테스트2",
    "writer": "sohee123",
    "content": "내용 없었는데 생겼음"
}

### 게시물 한 건 삭제
DELETE http://localhost:9999/shop/boards/1
Content-Type: application/json